--- # Run the date command on all hosts in Job Template avilable inventory
- hosts: all
  gather_facts: no
  tasks:
    - block:
      - name: install Apache, mysql 
        yum: name={{ item }} state=latest
        with_items:
          - httpd
          - mysqld
      - name: start Apache service
        service: name={{ item }} state=started
        with_items:
          - httpd
          - mysqld
      tags:
        - install
    - name: remove/delete Apache, mysql
      yum: name={{ item }} state=absent
      with_items:
        - httpd
        - mysql
      tags:
        - delete