--- # Run the date command on all hosts in Job Template avilable inventory
- hosts: all
  gather_facts: yes
  tasks:
    - name: install the latest version of Apache
      shell: date
    - name: install Apache
      yum: name=httpd state=latest
      tags:
        - install
    - name: start Apache service
      service: name=httpd state=started
      tags:
        - install
    - name: remove/delete Apache
      yum: name=httpd state=absent
      tags:
        - delete