--- # Run the date command on all hosts in Job Template avilable inventory
- hosts: all
  gather_facts: yes
  tasks:
    - block:
      - name: install Apache
        yum: name=httpd state=latest
      - name: start Apache service
        service: name=httpd state=started
      tags:
        - install
    - name: remove/delete Apache
      yum: name=httpd state=absent
      tags:
        - delete