--- # name: Execute a script
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    templates:
      RedHat72:  "ami-2051294a"
      AmazonLinux: "ami-6869aa05"
  tasks:
    - name: Set ami value based on user input Amazon Linux
      set_fact:
        ami: "{{ templates.RedHat72 }}"
      when: ami_image == "RedHat 7.2 Gold"
    - name: create instance
      ec2:
          assign_public_ip: no
          region: "{{ region }}"
          key_name: "{{ key_name }}"
          group_id: sg-bc61badb
          image: "{{ ami }}"
          instance_type: "{{ instance_type }}"
          vpc_subnet_id: "{{ subnet_id }}"
          count: 1
          instance_tags:
            Name: "{{ Host_Name_Tag }}"
            Project: "{{ Project_Tag }}"
            Description: "{{ Description_Tag }}"
            Environment: "{{ Environment_Tag }}"
          wait: yes
          wait_timeout: 500
      register: ec2
