--- # name: Execute a script
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    templates:
      RedHat72:  "ami-2051294a"
      AmazonLinux: "ami-6869aa05"
  tasks:
    - name: Set ami value based on user input Amazon Linux
      set_fact:
        ami: "{{ templates.AmazonLinux }}"
      when: AMI_Image == "Amazon Linux" 
    - name: Set ami value based on user input RedHat 7.2
      set_fact:
        ami: "{{ templates.RedHat72 }}"
      when: AMI_Image == "RedHat 7.2"
  tasks:
    - name: create instance
      ec2:
          assign_public_ip: no
          region: {{ Region }}
          key_name: {{ Key_Name }}
          group: {{ Security_Group }}
          image: {{ AMI_Image }}
          instance_type: {{ Instance_Type }}
          vpc_subnet_id: {{ Subnet_ID }}
          count: 1
          instance_tags:
            Name: {{ Host_Name_Tag }}
            Project: {{ Project_Tag }}
            Description: {{ Description_Tag }}
            Environment: {{ Environment_Tag }}
          wait: yes
          wait_timeout: 500
      register: ec2
