--- # Run the date command on all hosts in Job Template avilable inventory
- hosts: all
  gather_facts: yes
  tasks:
    - name: run shell date command - really just to prove accessibility
      shell: date
