--- # Run the date command on all hosts in Job Template avilable inventory
- hosts: all
  gather_facts: no
  vars:
    instance_ids:
      - 'i-bd15c24a'
    region: us-west-2
    subnet: subnet-722cvs23
  tasks:
    - name: Stop the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        vpc_subnet_id: '{{ subnet }}'
        state: stopped
        wait: True