--- # build basic VPC, SUBNET, INSTANCE
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_ids:
      - 'i-6e6a42e8'
    region: us-east-1
    subnet_id: subnet-199f476e
  tasks:
    - name: gather facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          instance-state-name: running
          vpc-id: vpc-6a7dc60f
          "tag:turnoffnightly": true
      register: instances
    - name: display facts about discovered instance using filter
      debug: var=instances
    - name: chabnge instance state
      ec2:
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_ids: '{{ instance_ids }}'
        state: running
