--- # Run the date command on all hosts in Job Template avilable inventory
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: install LYNX
      yum: name=httpd state=latest
    - name: Start the Web Server
      service: name=httpd state=started enabled=yes
